apiVersion: apps/v1
kind: Deployment
metadata:
  name: oneup
  labels:
    app: oneup
spec:
  selector:
    matchLabels:
      app: oneup
  template:
    metadata:
      labels:
        app: oneup
    spec:
      containers:
      - name: oneup
        image: oneup
        ports:
        - containerPort: 8000
