---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tilt-integration-user
  namespace: tilt-integration

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tilt-integration-user-full-access
  namespace: tilt-integration
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tilt-integration-user-view
  namespace: tilt-integration
subjects:
- kind: ServiceAccount
  name: tilt-integration-user
  namespace: tilt-integration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tilt-integration-user-full-access
